name: aur-release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  aur:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/aur

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            dist/aur/fcitx5-voice-input-*.tar.gz
            dist/aur/PKGBUILD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
